import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy — CODFLIP by The Growth Agency',
}

type Item = string | { term: string; text: string }

type Section = {
  num: string
  title: string
  body?: string | string[]
  list?: Item[]
}

const sections: Section[] = [
  {
    num: '1.',
    title: 'Introduction',
    body: [
      'Welcome to The Growth Agency.',
      'Kadadevaru Technology LLP ("us", "we", or "our") operates https://thegrowthagency.in (hereinafter referred to as "Service").',
      'This Privacy Policy governs your visit to https://thegrowthagency.in and explains how we collect, safeguard, and disclose information that results from your use of our Service. We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used herein have the same meanings as in our Terms of Service.',
      'Our Terms of Service govern all use of our Service and, together with this Privacy Policy, constitute your agreement with us.',
    ],
  },
  {
    num: '2.',
    title: 'Definitions',
    body: 'For the purposes of this Privacy Policy:',
    list: [
      { term: 'SERVICE', text: 'means the https://thegrowthagency.in website operated by Kadadevaru Technology LLP.' },
      { term: 'PERSONAL DATA', text: 'means data about a living individual who can be identified from those data, or from those data and other information either in our possession or likely to come into our possession.' },
      { term: 'USAGE DATA', text: 'is data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).' },
      { term: 'COOKIES', text: 'are small files stored on your device (computer or mobile device).' },
      { term: 'DATA CONTROLLER', text: 'means a natural or legal person who determines the purposes for which and the manner in which any personal data are processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.' },
      { term: 'DATA PROCESSORS (OR SERVICE PROVIDERS)', text: 'means any natural or legal person who processes data on behalf of the Data Controller. We may use the services of various Service Providers to process your data more effectively.' },
      { term: 'DATA SUBJECT', text: 'is any living individual who is the subject of Personal Data.' },
      { term: 'THE USER', text: 'is the individual using our Service. The User corresponds to the Data Subject.' },
      { term: 'MERCHANT', text: 'means the entity, company, firm, or organisation that has availed or is availing the Services of the Company for the purpose of facilitating interactions with its end-customers, and who, in connection with such use of the Services, collects, stores, processes, or otherwise handles the Personal Data of its end-customers for its own business purposes, acting as a Data Fiduciary in relation to such Personal Data.' },
      { term: 'MERCHANT END USER', text: 'means the end users or customers of the Merchant who access the Merchant’s website, mobile application, or any other e-commerce platform owned or operated by the Merchant.' },
      { term: 'MERCHANT END USER PERSONAL DATA', text: 'means any data about an individual Merchant End User who is identifiable by or in relation to such data.' },
    ],
  },
  {
    num: '3.',
    title: 'Information Collection and Use',
    body: 'We collect several different types of information for various purposes to provide and improve our Service to you.',
  },
  {
    num: '4a.',
    title: 'Personal Data',
    body: 'While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). This may include, but is not limited to:',
    list: [
      'Name and brand name',
      'Email address',
      'WhatsApp number',
      'Monthly order volume and annual revenue range (for audit qualification)',
      'Cookies and Usage Data',
    ],
  },
  {
    num: '',
    title: '',
    body: 'We may use your Personal Data to contact you with information about the FlipCOD service, upcoming features, and related updates. You may opt out of receiving any or all communications from us by emailing us at support@thegrowthagency.in.',
  },
  {
    num: '4b.',
    title: 'Usage Data',
    body: "We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device (\"Usage Data\"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.",
  },
  {
    num: '4c.',
    title: 'Tracking and Cookies Data',
    body: [
      'This website uses no tracking cookies or third-party analytics scripts. No cookie consent banner is required. We do not use Google Analytics, Facebook Pixel, or any similar tracking technology.',
      'If this policy changes in the future, we will notify you by updating this Privacy Policy and the date at the top of this page.',
    ],
  },
  {
    num: '5.',
    title: 'Use of Data',
    body: 'Kadadevaru Technology LLP uses the collected data for the following purposes:',
    list: [
      'To provide and maintain our Service',
      'To notify you about changes to our Service',
      'To allow you to participate in interactive features of our Service when you choose to do so',
      'To provide customer support',
      'To gather analysis or valuable information so that we can improve our Service',
      'To monitor the usage of our Service',
      'To detect, prevent, and address technical issues',
      'To contact you about the FlipCOD service and assess whether your store is eligible for onboarding',
      'To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection',
      'To provide you with notices about your account and/or subscription, including expiration and renewal notices',
      'For any other purpose with your consent',
    ],
  },
  {
    num: '6.',
    title: 'Retention of Data',
    body: [
      'We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.',
      'Form submissions are processed via our intake system and delivered to our inbox. We do not maintain a separate database of enquiries beyond what is operationally necessary. Client data is stored on secure, access-controlled systems and retained for as long as the engagement is active, plus 12 months after termination for legitimate business purposes.',
      'Usage Data is generally retained for a shorter period, except when this data is used to strengthen security or improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.',
    ],
  },
  {
    num: '7.',
    title: 'Transfer of Data',
    body: [
      'Your information, including Personal Data, may be transferred to and maintained on computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.',
      'Kadadevaru Technology LLP will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy. No transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place, including the security of your data and other personal information.',
    ],
  },
  {
    num: '8.',
    title: 'Disclosure of Data',
    body: 'We may disclose personal information that we collect, or that you provide, in the following circumstances:',
    list: [
      { term: 'Disclosure for Law Enforcement.', text: 'Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.' },
      { term: 'Business Transaction.', text: 'If we or our subsidiaries are involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.' },
      { term: 'Service Providers.', text: 'We may disclose your data to our subsidiaries, affiliates, or third-party service providers engaged to assist in delivering the Service, solely for that purpose.' },
      { term: 'With your consent.', text: 'We may disclose your information in any other cases with your prior consent.' },
      { term: 'Protection of rights.', text: 'We may disclose your information if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.' },
    ],
  },
  {
    num: '9.',
    title: 'WhatsApp Communications',
    body: [
      "If you become a client, your customers' data including order IDs, phone numbers, and purchase history is processed via WhatsApp Business API and your Shopify store in accordance with Meta's Business Platform Terms and Shopify's data policies. All messaging is TRAI/DLT compliant.",
      "We are a data processor on your behalf. You remain the data controller for your customer data. You represent and warrant that all consents obtained through your end-customers are in compliance with applicable third-party platform policies, including Meta's and WhatsApp's then-current business messaging policy.",
      'To the extent data obtained through WhatsApp interactions is subject to restrictions on secondary use under WhatsApp Policies, we shall apply such restrictions to the processing of such data.',
    ],
  },
  {
    num: '10.',
    title: 'Security of Data',
    body: 'The security of your data is important to us. However, please remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.',
  },
  {
    num: '11.',
    title: 'Your Data Protection Rights Under the General Data Protection Regulation (GDPR)',
    body: [
      'If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights covered by GDPR. We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.',
      'If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please email us at support@thegrowthagency.in.',
      'In certain circumstances, you have the following data protection rights:',
    ],
    list: [
      'The right to access, update, or delete the information we have on you',
      'The right of rectification to have inaccurate or incomplete information corrected',
      'The right to object to our processing of your Personal Data',
      'The right of restriction to request that we restrict the processing of your personal information',
      'The right to data portability to receive a copy of your Personal Data in a structured, machine-readable, and commonly used format',
      'The right to withdraw consent at any time where we rely on your consent to process your personal information',
    ],
  },
  {
    num: '',
    title: '',
    body: 'Please note that we may ask you to verify your identity before responding to such requests. You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data.',
  },
  {
    num: '12.',
    title: 'Your Rights Under the Digital Personal Data Protection Act, 2023 (DPDPA)',
    body: 'As a company operating in India, we comply with the Digital Personal Data Protection Act, 2023 (DPDPA) to the extent it has been implemented. You have the right to:',
    list: [
      'Obtain information about the Personal Data we hold about you and how it is processed',
      'Correct inaccurate or incomplete Personal Data',
      'Erase Personal Data that is no longer necessary for the purpose for which it was collected, subject to legal obligations',
      'Nominate another individual to exercise these rights on your behalf in the event of your death or incapacity',
    ],
  },
  {
    num: '',
    title: '',
    body: 'To exercise any of the above rights, please contact us at support@thegrowthagency.in. We will respond within 7 business days.',
  },
  {
    num: '13.',
    title: "Restriction on Processing Children's Personal Data",
    body: [
      'Our Services are not intended for use by children under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. You represent, warrant, and undertake that you shall not provide us with, or cause us to process, personal data of any individual under the age of 18 years without having first obtained verifiable parental or guardian consent for such processing.',
      'If you become aware that a child has provided us with Personal Data, please contact us at support@thegrowthagency.in. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our systems.',
    ],
  },
  {
    num: '14.',
    title: 'Service Providers',
    body: 'We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services, or to assist us in analysing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.',
  },
  {
    num: '15.',
    title: 'Links to Other Sites',
    body: "Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.",
  },
  {
    num: '16.',
    title: 'Changes to This Privacy Policy',
    body: 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service prior to the change becoming effective and will update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
  },
  {
    num: '17.',
    title: 'Company Details',
    list: [
      { term: 'Company Brand Name:', text: 'The Growth Agency' },
      { term: 'Legal Entity Name:', text: 'Kadadevaru Technology LLP' },
      { term: 'LLPIN:', text: 'ACO-0082' },
      { term: 'Registered Address:', text: 'Arihant Atria, Saptapur, Dharwad – 580001, Karnataka, India' },
      { term: 'Email:', text: 'support@thegrowthagency.in' },
      { term: 'WhatsApp:', text: '+91 96642 00912' },
    ],
  },
  {
    num: '18.',
    title: 'Contact Us',
    body: 'If you have any questions about this Privacy Policy, please contact us:',
    list: [
      { term: 'By email:', text: 'support@thegrowthagency.in' },
      { term: 'By WhatsApp:', text: '+91 96642 00912' },
      { term: 'By post:', text: 'Arihant Atria, Saptapur, Dharwad – 580001, Karnataka, India' },
    ],
  },
]

function renderBody(body: string | string[]) {
  const paragraphs = Array.isArray(body) ? body : [body]
  return paragraphs.map((p, i) => (
    <p
      key={i}
      style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '15px', color: 'var(--text-2)', lineHeight: 1.8, marginBottom: i < paragraphs.length - 1 ? '14px' : 0 }}
    >
      {p}
    </p>
  ))
}

function renderList(list: Item[]) {
  return (
    <ul style={{ listStyle: 'disc', paddingLeft: '22px', marginTop: '14px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
      {list.map((item, i) => (
        <li
          key={i}
          style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '15px', color: 'var(--text-2)', lineHeight: 1.7 }}
        >
          {typeof item === 'string' ? (
            item
          ) : (
            <>
              <strong style={{ color: 'var(--text)', fontWeight: 600 }}>{item.term}</strong> {item.text}
            </>
          )}
        </li>
      ))}
    </ul>
  )
}

export default function PrivacyPolicy() {
  return (
    <main style={{ background: 'var(--bg)', minHeight: '100vh', padding: '120px 24px 80px' }}>
      <div style={{ maxWidth: '720px', margin: '0 auto' }}>

        {/* Back */}
        <a
          href="/"
          style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '14px', color: 'var(--text-3)', display: 'inline-flex', alignItems: 'center', gap: '6px', marginBottom: '48px', textDecoration: 'none' }}
        >
          ← Back to home
        </a>

        {/* Header */}
        <div style={{ marginBottom: '48px' }}>
          <p style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '11px', fontWeight: 600, color: '#10B981', textTransform: 'uppercase', letterSpacing: '0.14em', marginBottom: '16px' }}>
            CODFLIP by The Growth Agency
          </p>
          <h1 style={{ fontFamily: 'var(--font-syne)', fontWeight: 800, fontSize: 'clamp(28px, 4vw, 44px)', color: 'var(--text)', lineHeight: 1.1, marginBottom: '12px' }}>
            Privacy Policy
          </h1>
          <p style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '14px', color: 'var(--text-4)' }}>
            Last updated: April 2026
          </p>
          <p style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '13px', color: 'var(--text-4)', marginTop: '8px', lineHeight: 1.6 }}>
            Kadadevaru Technology LLP · Arihant Atria, Saptapur, Dharwad – 580001, Karnataka, India
          </p>
        </div>

        {/* Sections */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '40px' }}>
          {sections.map((s, idx) => (
            <div key={idx}>
              {s.title && (
                <h2 style={{ fontFamily: 'var(--font-syne)', fontWeight: 700, fontSize: '18px', color: 'var(--text)', marginBottom: '10px' }}>
                  {s.num} {s.title}
                </h2>
              )}
              {s.body && renderBody(s.body)}
              {s.list && renderList(s.list)}
            </div>
          ))}
        </div>

      </div>
    </main>
  )
}
