import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — CODFLIP by The Growth Agency',
}

type Item = string | { term: string; text: string }

type Section = {
  num: string
  title: string
  body?: string | string[]
  list?: Item[]
}

const sections: Section[] = [
  {
    num: '',
    title: '',
    body: [
      'This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.',
      'The domain name https://thegrowthagency.in is owned and managed by Kadadevaru Technology LLP. Please read these Terms of Service carefully, as they contain the terms and conditions governing your use of the Platform and any content, data, information, software, or services that the Company may make available through the Platform. By accessing or using the Platform, you agree to be bound by these Terms. Please do not access or use the Platform if you do not agree with any of the terms provided herein.',
      'The Company reserves the right, at its sole discretion, to change, modify, add, or remove portions of these Terms at any time. We will notify you of material changes via email or a prominent notice on the Platform. Your continued use of the Platform after the posting of changes shall constitute your acceptance of the revised Terms.',
    ],
  },
  {
    num: '1.',
    title: 'Definitions',
    body: 'In these Terms, unless the context otherwise requires:',
    list: [
      { term: '"Access Codes"', text: 'means passwords and user IDs necessary to access and use the Platform.' },
      { term: '"Authorised Users"', text: 'means a single employee, consultant, or other individual who needs to access and use the Platform in the performance of their duties for you and is granted access pursuant to your authorisation.' },
      { term: '"Data"', text: 'means any documents, files, information, or data stored or processed through use of the Platform that concerns your business, technology, or compliance-related data, including but not limited to details of your customers, their names, addresses, reports, and analyses.' },
      { term: '"Derived Data"', text: 'means insights, analytics, behavioural consumer data, benchmarking information, reports, aggregated datasets, statistical models, algorithms, machine learning models, and any other outputs derived by the Company through the processing, aggregation, or analysis of Data and Merchant End User Personal Data. Derived Data shall not include the underlying raw Data and Merchant End User Personal Data.' },
      { term: '"Force Majeure"', text: 'means any circumstance or event beyond the reasonable control of the Company that results in the Company being unable to observe or perform its obligations on time, including WhatsApp platform outages, Meta policy changes, and Shopify service interruptions.' },
      { term: '"Intellectual Property"', text: 'includes all intellectual property rights existing anywhere in the world, including agent architectures, prompt systems, automation workflows, proprietary methodologies, source code, trademarks, trade names, copyrights, patents, designs, and any enhancements or derivative works thereof.' },
      { term: '"Merchant"', text: 'has the meaning ascribed to it in the Privacy Policy.' },
      { term: '"Merchant End User"', text: 'has the meaning ascribed to it in the Privacy Policy.' },
      { term: '"Privacy Law"', text: 'means the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011, CERT-In guidelines, and the Digital Personal Data Protection Act, 2023 (as implemented).' },
      { term: '"Security Breach"', text: 'means any unauthorised access, use, disclosure, damage, or destruction of the Platform and/or any data on the Platform.' },
      { term: '"Services"', text: 'means WhatsApp-based AI retention automation for Shopify D2C brands, including agent setup, WhatsApp Business API integration, Shopify sync, ongoing agent management, and periodic CAC reporting, as further described in the engagement agreement.' },
      { term: '"Update"', text: 'means a new release of the Platform containing bug fixes and minor modifications.' },
      { term: '"Upgrade"', text: 'means a new release of the Platform containing significant new features or functionality.' },
    ],
  },
  {
    num: '2.',
    title: 'Membership Eligibility',
    body: "Use of the Platform is available only to natural persons who can enter into legally binding contracts under the Indian Contract Act, 1872. Persons who are 'incompetent to contract' within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents, and persons of unsound mind are not eligible to use the Platform. Any person under the age of 18 shall not register on or transact on the Platform without verifiable consent from their legal guardian. The Company reserves the right to terminate any person's membership and/or refuse access to the Platform if such person is found to be ineligible.",
  },
  {
    num: '3.',
    title: 'Acceptance of Terms',
    body: 'You can accept these Terms by: (a) signing up with the Company and logging on to the Platform using your Login Credentials; or (b) by clicking to accept these Terms, if and when prompted on the Platform. If you are unwilling or unable to be legally bound by these Terms, please do not use the Platform.',
  },
  {
    num: '4.',
    title: 'Opening an Account',
    body: [
      'Registration on the Platform is mandatory to avail the Services. You shall be provided with Access Codes necessary to access the Platform through your User Account. You shall be responsible for the confidentiality of your Access Codes and shall not share them with any third party.',
      'You shall be fully responsible for all activities that occur under your User Account. The Company shall not be responsible for any loss or damage caused to you due to unauthorised use of or access to the Platform. The Company shall be entitled to immediately disable all Access Codes upon: (a) your written request; or (b) an actual or threatened Security Breach, with or without notice to you.',
      'You confirm that all information provided at sign-up is and will be true, accurate, up-to-date, and complete at all times. If any information provided is found to be untrue or inaccurate, the Company shall have the right to suspend, terminate, or block access to the User Account.',
    ],
  },
  {
    num: '5.',
    title: 'Account Confidentiality Obligations',
    body: [
      'You agree that the sole responsibility of maintaining the security and confidentiality of your Login Credentials rests with you at all times. You shall not share these Login Credentials with any third party. You and your Authorised Users are solely responsible for all activities that occur under the User Account.',
      'In case of any misappropriation or unauthorised access to the User Account, you agree to communicate the same to the Company immediately at support@thegrowthagency.in.',
    ],
  },
  {
    num: '6.',
    title: 'Obligations',
    body: 'You hereby undertake and covenant that you shall, and shall cause your Authorised Users to:',
    list: [
      'Install the latest Upgrades of the Platform and comply with all related instructions from the Company',
      'Provide Shopify read-only API access and a valid WhatsApp Business number',
      'Ensure your business is registered on DLT before message template submission (we assist with this process but you remain the registered principal entity)',
      'Immediately report any error encountered on the Platform and not attempt to modify or correct such errors without specific written instruction from the Company',
      'Prevent unauthorised access to the Platform and notify the Company immediately of any such unauthorised use or known breach of security',
      'Not use the Platform in violation of these Terms or applicable law',
      'Maintain a proper operating environment for the use of the Platform in accordance with any guidance from the Company',
      'Comply with all applicable Privacy Laws in respect of any Merchant End User Personal Data collected, processed, or stored by you',
      "Not use the Service to send content that violates WhatsApp's Business Messaging Policy or Indian telecommunications law",
    ],
  },
  {
    num: '7.',
    title: 'Services',
    body: [
      'The Company provides WhatsApp-based AI retention automation for Shopify D2C brands. Services include agent setup, WhatsApp Business API integration, Shopify sync, ongoing agent management, and periodic CAC reporting. The specific scope is defined in the engagement agreement signed before onboarding.',
      'Subject to these Terms, the Company grants you a non-exclusive, non-transferable, revocable, non-assignable, and limited right to access and use the Platform for the purpose of availing the Services in accordance with these Terms, for your internal business use.',
      'The Company shall not be liable for unavailability of Services due to: (a) a Force Majeure event; (b) scheduled downtime; (c) outages based on your networks, domain name server issues, or other third-party services; or (d) outages to remedy a security vulnerability or as required under applicable law.',
      "The Services are provided on an 'as is' basis. The Company makes no representations concerning the quality of the Platform or the Services and does not promise that the Platform or Services will be error-free, bug-free, or will operate without interruption.",
    ],
  },
  {
    num: '8.',
    title: 'Free Trial',
    body: 'CODFLIP offers eligible Shopify merchants a 7-day free trial of the Pro plan upon first activation. During the free trial, all Pro plan features are available at no charge. No payment is required during the free trial period, and the trial does not constitute a binding service agreement. If you do not cancel before the trial period ends, the Pro plan subscription (₹999/month + 3% conversion fee) will activate automatically. A perpetual Free plan (up to 50 COD orders per billing period) is also available at no cost and does not require a trial period. The Company reserves the right to modify the duration or eligibility criteria of the free trial at its sole discretion.',
  },
  {
    num: '9.',
    title: 'Support Services',
    body: [
      'The Company shall use reasonable efforts consistent with prevailing industry standards to maintain the Services in a manner that minimises errors and interruptions. The Company will provide technical support via email and WhatsApp during business hours on weekdays (9:00 AM – 6:00 PM IST), excluding public holidays.',
      "The Company will use commercially reasonable efforts to respond to all helpdesk requests within 1 business day. Services shall be available 99% of the time measured monthly, excluding scheduled maintenance and events beyond the Company's reasonable control.",
    ],
  },
  {
    num: '10.',
    title: 'Data and Security',
    body: [
      'Title to, and all Intellectual Property in, the Data and Merchant End User Personal Data remains your property. You grant the Company a non-exclusive, fully paid-up licence to use, store, copy, or modify the Data and Merchant End User Personal Data on a confidential basis solely for: (a) the provision of Services; or (b) any other purpose in connection with the exercise of the Company\'s rights and performance of its obligations under these Terms.',
      'Notwithstanding the foregoing, Intellectual Property in Derived Data created by the Company through the processing, aggregation, or analysis of Data and Merchant End User Personal Data shall vest in and be the exclusive property of the Company. Derived Data shall not include the underlying raw Data and Merchant End User Personal Data.',
      'The Company may use artificial intelligence technologies, including large language models, to analyse Data for the purpose of improving, developing, and enhancing the Services. The Company may share Derived Data with third-party service providers in an anonymised and aggregated manner such that no brand, merchant, customer, or individual can be directly or indirectly identified.',
      "If you transfer any Personal Data to the Company, you warrant that you are duly authorised to do so and that you did so lawfully in compliance with relevant Privacy Laws, including by obtaining the Merchant End User's consent through affirmative action.",
      'You agree not to provide any health, payment card, or similarly sensitive personal information unless it is a supported feature expressly agreed in writing.',
    ],
  },
  {
    num: '11.',
    title: 'Third-Party Compliance',
    body: "You represent and warrant that consent obtained through your end-customer is in compliance with applicable third-party platform policies, including Meta's and WhatsApp's then-current business messaging policy. To the extent data obtained through WhatsApp interactions is subject to restrictions on secondary use under WhatsApp Policies, the Company shall apply such restrictions and notify you of them in a timely manner.",
  },
  {
    num: '12.',
    title: 'Payment Terms',
    body: [
      'CODFLIP offers two plans: (a) a Free plan at ₹0 per month, limited to 50 COD orders per billing period with no variable conversion fee; and (b) a Pro plan at ₹999 per month plus a variable conversion fee of 3% of the total order value of each successfully converted order. The Pro plan includes a 7-day free trial upon first activation. All pricing is inclusive of the features described in the plan selected at the time of installation and may be updated from time to time in accordance with this clause.',
      'The Pro plan flat monthly fee of ₹999 is payable in advance at the start of each billing cycle and is billed through the Shopify App Store billing system. The variable conversion fee of 3% is calculated on the total_price of each converted order at the time of conversion and is billed at the end of each calendar month through the Shopify App Store billing system.',
      'All prices are exclusive of GST where applicable. Any processing fees levied by the Shopify payment system or any other payment gateway at the time of making payment shall be borne by you.',
      'Invoices shall be treated as final and confirmed unless you raise any discrepancy within 2 business days of receipt. The parties shall work together in good faith to resolve any such discrepancy.',
      'Any revised pricing shall be communicated to you via email or the Platform dashboard with reasonable prior notice. Your continued use of the Service following the effective date of revised pricing shall constitute your acceptance of such revised pricing.',
      'In the event of failure to pay within 14 days of an invoice falling due, the Company reserves the right to suspend access to the Service, deactivate pending flip sequences, and disable coupon generation until outstanding amounts are settled.',
    ],
  },
  {
    num: '13.',
    title: 'Outcome-Aligned Billing',
    body: [
      'The variable conversion fee of 3% (applicable to the Pro plan) is charged exclusively on COD orders that are successfully converted to prepaid through the CODFLIP platform. A conversion is recognised when: (a) the customer completes payment via the UPI or prepaid link provided by the platform; and (b) the Shopify order status updates to paid with a non-COD payment gateway, confirmed by the platform\'s conversion detection logic.',
      'No variable fee is charged on orders that are scored and targeted but not converted, on orders that are skipped or excluded by the eligibility engine, or on orders where the customer opts out or allows the offer to expire without payment. The Free plan has no variable conversion fee of any kind.',
      'The flat monthly subscription fee for the Pro plan is charged regardless of conversion volume and is non-refundable once the billing cycle has commenced, except as otherwise expressly agreed in writing. No fee is charged for the Free plan.',
      'In the event of a billing dispute regarding a specific conversion event, you may raise a dispute within 7 days of the relevant invoice. The Company will provide a full audit log of the conversion event including webhook receipt timestamp, coupon usage record, and payment gateway confirmation. Undisputed amounts remain payable within the original due date.',
    ],
  },
  {
    num: '14.',
    title: 'Cancellation and Termination of Subscription',
    body: [
      'You may cancel your FlipCOD subscription at any time by: (a) uninstalling the app from your Shopify store; or (b) sending a written cancellation notice to support@thegrowthagency.in with your store domain and the effective date of cancellation.',
      'Cancellation takes effect at the end of the current billing cycle. The flat monthly fee for the current billing cycle in which cancellation occurs is non-refundable. Variable conversion fees accrued up to the date of cancellation remain payable and will be billed in the final invoice.',
      'Upon cancellation: (a) all pending flip sequences will be deactivated; (b) all active coupons issued by the platform will be deactivated in your Shopify store; (c) the Shopify webhook subscriptions registered by the platform will be removed; and (d) your data will be retained for 12 months following termination for audit and dispute resolution purposes, after which it will be deleted or anonymised in accordance with the Privacy Policy.',
      'The Company may terminate your subscription immediately upon written notice in the event of: (a) material breach of these Terms that is not remedied within 7 days of notice; (b) fraudulent or abusive use of the platform including manipulation of the conversion detection logic; or (c) non-payment of undisputed amounts beyond 30 days of the due date.',
    ],
  },
  {
    num: '15.',
    title: 'Intellectual Property',
    body: [
      'All agent architectures, prompt systems, automation workflows, and proprietary methodologies remain the Intellectual Property of The Growth Agency. You retain ownership of your customer data and brand content. You shall not, directly or indirectly: (a) decompile, disassemble, or reverse engineer the Platform; (b) modify, create derivative works from, or translate the Platform; (c) use the Services for the benefit of a third party; or (d) use the Platform in violation of these Terms.',
      'The Company grants you a royalty-free, fully paid-up, worldwide, and non-exclusive licence to use your name and logo for the purpose of publicising its engagement with you, unless you notify us in writing that you object to such use.',
    ],
  },
  {
    num: '16.',
    title: 'Acceptable Use of the Platform',
    body: 'You agree that during your use of the Platform, you shall not host, upload, transmit, or share any information that:',
    list: [
      'Belongs to another person or entity to which you do not have any right',
      'Is grossly harmful, harassing, defamatory, obscene, pornographic, libellous, invasive of another person’s privacy, hateful, or racially or ethnically objectionable',
      'Is misleading in any way or involves the transmission of spam or unsolicited mass communications',
      'Infringes upon or violates any third party’s intellectual property or privacy rights',
      'Involves providing instructional information about illegal activities',
      'Threatens the unity, integrity, defence, security, or sovereignty of India or friendly relations with foreign states',
      'Contains software viruses, trojan horses, worms, or other computer programming routines designed to interrupt, destroy, or limit the functionality of any computer resource',
      'Violates any applicable law for the time being in force',
    ],
  },
  {
    num: '17.',
    title: 'Disclaimer of Warranties',
    body: "THE PLATFORM AND ALL INFORMATION, CONTENT, MATERIALS, AND SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE PLATFORM ARE PROVIDED BY THE COMPANY ON AN 'AS IS', 'AS AVAILABLE' BASIS, WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND. THE COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE PLATFORM OR THE ACCURACY OR COMPLETENESS OF THE CONTENTS. TO THE FULL EXTENT PERMITTED BY LAW, THE COMPANY DISCLAIMS ANY AND ALL REPRESENTATIONS AND WARRANTIES WITH RESPECT TO THE PLATFORM AND ITS CONTENTS, WHETHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF TITLE, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE.",
  },
  {
    num: '18.',
    title: 'Limitation of Liability',
    body: 'Our total liability to you for any claim arising under or related to this Service is limited to the fees paid in the 3 months preceding the claim. We are not liable for indirect, incidental, or consequential damages including lost revenue, lost profits, or business interruption. We are not liable for WhatsApp platform outages, Meta policy changes, or Shopify service interruptions.',
  },
  {
    num: '19.',
    title: 'Indemnity',
    body: 'You hereby agree to indemnify, defend, and hold harmless the Company, its affiliates, and their respective agents, officers, directors, employees, successors, and assigns from and against any and all liabilities, damages, losses, expenses, claims, demands, suits, fines, or judgments arising out of or relating to: (a) use of the Platform in breach of these Terms; (b) infringement of any third-party Intellectual Property rights or violation of applicable law resulting from the Data; or (c) breach of any representation or covenant set forth in these Terms by you.',
  },
  {
    num: '20.',
    title: 'Confidentiality',
    body: 'You agree and acknowledge that you may receive certain confidential information and hereby undertake to keep such confidential information in accordance with these Terms and applicable laws. You agree not to disclose any confidential information provided by the Company to any third party without the prior written consent of the Company.',
  },
  {
    num: '21.',
    title: 'Term and Termination',
    body: [
      'Unless otherwise agreed in the engagement agreement, the initial lock-in for the Services shall be for a period of 1 (one) month from the date of signing up. Following the initial term and unless otherwise terminated as provided herein, the Services shall automatically renew on a monthly basis until a party serves the other with prior written notice of termination.',
      'You may cancel your subscription at any time by uninstalling the app or sending written notice to support@thegrowthagency.in with your store domain. The Company may terminate the User Account at any time, in its sole discretion, for any reason or no reason, including violation of these Terms, upon written notice where practicable.',
      'On termination: (a) all licences granted herein shall stand terminated and you shall immediately cease use of the Platform and Services; (b) you must pay all outstanding fees and charges for the rights and Services provided prior to the date of termination; and (c) all pending flip sequences will be deactivated, active coupons will be cancelled, and variable conversion fees accrued up to the date of termination remain payable and will be settled in the final invoice.',
    ],
  },
  {
    num: '22.',
    title: 'Severability and Waiver',
    body: 'These Terms, together with the Privacy Policy and other referenced material, constitute the entire agreement between you and the Company and supersede all prior or contemporaneous communications and proposals (whether oral, written, or electronic) between you and the Company with respect thereto. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Terms will otherwise remain in full force and effect. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder.',
  },
  {
    num: '23.',
    title: 'Assignment',
    body: 'The relationship between the parties shall be that of independent contractors. You shall not assign your rights and obligations under these Terms without the prior written consent of the Company. The Company shall be entitled, without your prior written consent, to assign or transfer its rights and obligations under these Terms to any of its affiliates, or any successor entity in connection with a merger, acquisition, reorganisation, or sale of substantially all of its assets. The Company shall provide you with written notice of any such assignment within a reasonable period of time.',
  },
  {
    num: '24.',
    title: 'Governing Law and Dispute Resolution',
    body: 'These Terms shall be governed by and interpreted in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of Mumbai, Maharashtra.',
  },
  {
    num: '25.',
    title: 'Contact Us',
    body: 'If you have questions or concerns about these Terms, please contact us:',
    list: [
      { term: 'By email:', text: 'support@thegrowthagency.in' },
      { term: 'By WhatsApp:', text: '+91 96642 00912' },
      { term: 'By post:', text: '608, Arihant Atria, Saptapur, Dharwad – 580001, Karnataka, India' },
    ],
  },
]

function renderBody(body: string | string[]) {
  const paragraphs = Array.isArray(body) ? body : [body]
  return paragraphs.map((p, i) => (
    <p
      key={i}
      style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '15px', color: 'var(--text-2)', lineHeight: 1.8, marginBottom: i < paragraphs.length - 1 ? '14px' : 0 }}
    >
      {p}
    </p>
  ))
}

function renderList(list: Item[]) {
  return (
    <ul style={{ listStyle: 'disc', paddingLeft: '22px', marginTop: '14px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
      {list.map((item, i) => (
        <li
          key={i}
          style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '15px', color: 'var(--text-2)', lineHeight: 1.7 }}
        >
          {typeof item === 'string' ? (
            item
          ) : (
            <>
              <strong style={{ color: 'var(--text)', fontWeight: 600 }}>{item.term}</strong> {item.text}
            </>
          )}
        </li>
      ))}
    </ul>
  )
}

export default function Terms() {
  return (
    <main style={{ background: 'var(--bg)', minHeight: '100vh', padding: '120px 24px 80px' }}>
      <div style={{ maxWidth: '720px', margin: '0 auto' }}>

        {/* Back */}
        <a
          href="/"
          style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '14px', color: 'var(--text-3)', display: 'inline-flex', alignItems: 'center', gap: '6px', marginBottom: '48px', textDecoration: 'none' }}
        >
          ← Back to home
        </a>

        {/* Header */}
        <div style={{ marginBottom: '48px' }}>
          <p style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '11px', fontWeight: 600, color: '#10B981', textTransform: 'uppercase', letterSpacing: '0.14em', marginBottom: '16px' }}>
            CODFLIP by The Growth Agency
          </p>
          <h1 style={{ fontFamily: 'var(--font-syne)', fontWeight: 800, fontSize: 'clamp(28px, 4vw, 44px)', color: 'var(--text)', lineHeight: 1.1, marginBottom: '12px' }}>
            Terms of Service
          </h1>
          <p style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '14px', color: 'var(--text-4)' }}>
            Last updated: April 2026
          </p>
          <p style={{ fontFamily: 'var(--font-dm-sans)', fontSize: '13px', color: 'var(--text-4)', marginTop: '8px', lineHeight: 1.6 }}>
            Kadadevaru Technology LLP · 608, Arihant Atria, Saptapur, Dharwad – 580001, Karnataka, India
          </p>
        </div>

        {/* Sections */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '40px' }}>
          {sections.map((s, idx) => (
            <div key={idx}>
              {s.title && (
                <h2 style={{ fontFamily: 'var(--font-syne)', fontWeight: 700, fontSize: '18px', color: 'var(--text)', marginBottom: '10px' }}>
                  {s.num} {s.title}
                </h2>
              )}
              {s.body && renderBody(s.body)}
              {s.list && renderList(s.list)}
            </div>
          ))}
        </div>

      </div>
    </main>
  )
}
